# -*- org-confirm-babel-evaluate: nil -*-
#+TITLE:     Serial Drone Collider (WT)
#+AUTHOR:    Michal Seta
#+EMAIL:     
#+DATE:      2015-09-08
#+LANGUAGE:  en
#+INFOJS_OPT: view:showall toc:t ltoc:t mouse:underline path:http://orgmode.org/org-info.js
#+LINK_HOME: http://home.fnal.gov/~neilsen
#+LINK_UP: http://home.fnal.gov/~neilsen/notebook
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/notebook.css" />
#+LaTeX_CLASS: article
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: H:2 num:nil toc:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t date:t tags:nil
#+STARTUP: showall

* Drones, collisions in series

This piece is motivated by a call that Sandeep Bhagwati has issued for a tribute to the Austrian composer, Anton Webern. On September 15, 2015, the day of Webern's tragic death, Karlheinz Essl is launching a tribute called World Wide Webern where he invites people around the world to use his /Webern Clock/ to chime a melody using Webern's row(s). Sandeep will occupy Matralab on that day.

For that occasion, I thought that it would be interesting to hear Webern's atonal music in different tunings. For this particular exercise, I have chosen the source row derived from his unfinished Opus 32 and fed it through some simple manipulations and sent it to some complex instruments that play relatively long notes. The pieces is to play at every quarter after hour. Each rendition lasts less than 15 minutes and generates new music material. The synthesized sounds will unfold the Webern rows.

The words /drone/  and /serial/ are used used intentionally in an ambiguous juxtaposition.

** Tuning

Should someone care and want to play something like that on a guitar.

\vspace{18pt}

Standard tuning.
#+BEGIN_SRC lilypond :file scores/tunings.eps 

  \header{tagline=##f}
  \include "english.ly"
  mynotes = \relative c, {
    \override Staff.BarLine #'transparent = ##t
  \override Stem #'transparent = ##t 
    e2\6 a\5 d\4 g\3 b\2 e\1
  }
  \score {   
  <<
    \new Staff {
      \set Staff.midiInstrument = #"electric guitar (clean)" 
      \clef "treble_8"
      
      \mynotes
      \override BarLine #'transparent = ##t
      
    }
  >>   
    \midi{}
    \layout{}
  }
#+END_SRC

** The source row

The source row is given with a guitar tablature in order to accomodate any guitarists out there.

\vspace{18pt}

#+BEGIN_SRC lilypond :file scores/basicRow.eps

  \header{tagline=##f}
  \include "english.ly"
  
  the Row = \relative c {
    \override Staff.BarLine #'transparent = ##t
    \override Stem #'transparent = ##t 
    fs2 g af f' e ef b bf a c cs d

  }
  
  \score { 
    <<
      \new Staff {
        \set Staff.midiInstrument = #"electric guitar (clean)" 
        \clef "treble_8"
        
        \theRow
        \override BarLine #'transparent = ##t
        
      }
      \new TabStaff {
        \tabFullNotation
        \set Staff.stringTunings = \stringTuning <e, a, d g b e'>
        \theRow
        \override BarLine #'transparent = ##t
      }
    >>    
    
    \midi { }
    \layout { }
  }


#+END_SRC
\vspace{18pt}
This is the source row that was used by Anton Webern to write his opus 32, unfinished due to his premature death. [fn:1] This source row was given to an algorithm that figures out the other three forms (R, I, RI) and feeds it to drone synths.
The algorythms are rather simple, several voices play the row in its various forms, transposed a few intervals. The forms and transposition intervals are chosen interactively (although the actual interaction process has not been established yet). 

* Acknowledgement

Having been inspired by Anton Webern way back, I could not have missed this opportunity to give him a tribute. Big thanks to Sandeep Bhagwati for the opportunity to participate in this offering. And of course props to Karlheinz Essl for the initiative.

Michał Seta

* Footnotes

[fn:1] Shere, David Matthew, A Survey of Webern's Life and Compositional Vocabulary
